openapi: 3.0.0
info:
  version: 1.0.13
  title: Dynamic Role Assignment API v1.0
  description: ""
tags:
  - name: Dynamic Role Assignment
paths:
  /account/role:
    post:
      tags:
        - Dynamic Role Assignment
      operationId: assignUserToRole
      description: >
        Assign the authenticated user to a role. The role is unique identified
        by its name.
      parameters:
        - in: header
          name: authorization
          description: >-
            The access token granted to the client application after user
            authentication. The role is assigned to the user the client
            application is acting on behalf of.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoleDefinition"
      responses:
        "201":
          description: The role assignment is successful.
        "400":
          description: Required parameters are missing or invalid.
        "401":
          description: Missing bearer token.
        "403":
          description: Bearer token is expired or does not have 'manage-role' scope.
        "412":
          description: User is already assigned to this role or the role does not exist.
    delete:
      tags:
        - Dynamic Role Assignment
      operationId: unassignUserFromRole
      description: >-
        Removes the assignment of the authenticated user to the role, uniquely
        identified by its name.
      parameters:
        - in: header
          name: authorization
          description: >-
            The access token granted to the client application after user
            authentication. The role is unassigned from the user the client
            application is acting on behalf of.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoleDefinition"
      responses:
        "200":
          description: The role assignment is successfully removed.
        "400":
          description: Required parameters are missing or invalid.
        "401":
          description: Missing bearer token.
        "403":
          description: Bearer token is expired or does not have 'manage-role' scope.
        "412":
          description: User is not assigned to this role or the role does not exist.
servers:
  - url: /api/v1
components:
  securitySchemes:
    auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: http://authserver/login
          tokenUrl: http://authserver/oauth2/token
          scopes:
            manage-user: allows modifying a User resource
