openapi: 3.0.0
info:
  version: 1.0.0
  title: Bulk User Management API v1.0
  description: ""
tags:
  - name: Bulk User Management
paths:
  /users/registration/batch:
    post:
      tags:
        - Bulk User Management
      operationId: batchUserRegistration
      description: Issue a bulk user registration batch request.
      parameters:
        - in: header
          name: authorization
          description: The access token associated to the session.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/BulkRegistrationRequest"
        description: the body of the User JSON object.
        required: true
      responses:
        "202":
          description: Request accepted.
          headers:
            Location:
              description: >
                A Location header showing the URI where information pertaining
                to the current status

                of the scheduled batch operation can be queried. eg. Location: /api/v1/batch/{{id}}
              schema:
                type: string
        "400":
          description: Required parameters are missing or invalid.
        "401":
          description: Missing bearer token.
        "403":
          description: Bearer token is expired, or it doesn't have the 'create-user' scope.
  /users/roles/batch:
    post:
      tags:
        - Bulk User Management
      operationId: batchRoleManagement
      description: Issue a bulk user role update batch request.
      parameters:
        - in: header
          name: authorization
          description: The access token associated to the session.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/BulkRolesRequest"
        description: the body of the User JSON object.
        required: true
      responses:
        "202":
          description: Request accepted.
          headers:
            Location:
              description: >
                A Location header showing the URI where information pertaining
                to the current status

                of the scheduled batch operation can be queried. eg. Location: /api/v1/batch/{{id}}
              schema:
                type: string
        "400":
          description: Required parameters are missing or invalid.
        "401":
          description: Missing bearer token.
        "403":
          description: Bearer token is expired, or it doesn't have the 'create-user' scope.
servers:
  - url: /api/v1
components:
  securitySchemes:
    auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: http://authserver/login
          tokenUrl: http://authserver/oauth2/token
          scopes:
            create-user: allows modifying a User resource
  schemas:
    BulkRolesRequest:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: user unique ID (UID)
        operation:
          type: string
          enum:
            - ADD
            - REMOVE
            - REPLACE
          description: The operation type for this update
        roles:
          type: array
          items:
            type: string
          description: The names of the roles to be modified for the user
      required:
        - id
        - operation
        - roles
    BulkRegistrationRequest:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: user unique ID (UID)
        email:
          type: string
          format: email
          pattern: ^[^()!&/;%*@\s]+@[^()!&/;%*@\s]+\.[^()!&/;%*@\s]+$
          description: email used for registration
        firstName:
          type: string
          minLength: 1
          description: first name
        lastName:
          type: string
          minLength: 1
          description: last name
        roles:
          type: array
          items:
            type: string
          description: The names of the roles to be assigned to the user
      required:
        - email
        - firstname
        - lastname