name: Java CI with Gradle

on:
  push:
    branches:
      - master
      - refs/tags/*
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build
        run: ./gradlew check
